# Generated by Django 6.0.5 on 2026-05-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_logger_api', '0002_category_musclegroup_exercise_logexercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
