# Generated by Django 6.0.5 on 2026-05-29 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_logger_api', '0003_alter_exercise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_logs', to='workout_logger_api.category'),
        ),
    ]
