# Generated by Django 6.0.5 on 2026-05-29 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_logger_api', '0004_workoutlog_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='workout_logger_api.workoutlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'log')},
            },
        ),
    ]
